# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

---
# Conditionally disable springdoc on missing api-docs profile
spring:
  config:
    activate:
      on-profile: '!api-docs'
springdoc:
  api-docs:
    enabled: false
---
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - health
          - info
          - jhimetrics
          - jhiopenapigroups
          - logfile
          - loggers
          - prometheus
          - threaddump
          - caches
          - liquibase
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
    jhimetrics:
      enabled: true
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60
  observations:
    key-values:
      application: ${spring.application.name}
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    data:
      repository:
        autotime:
          enabled: true
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: onlineSatoriPlatform
  docker:
    compose:
      enabled: true
      lifecycle-management: start-only
      file: src/main/docker/services.yml
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: '@spring.profiles.active@'
    group:
      dev:
        - dev
        - api-docs
        # Uncomment to activate TLS for the dev profile
        #- tls
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.timezone.default_storage: NORMALIZE
      hibernate.type.preferred_instant_jdbc_type: TIMESTAMP
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          authority-prefix: ''
          authorities-claim-name: auth
  task:
    execution:
      thread-name-prefix: online-satori-platform-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: online-satori-platform-scheduling-
      pool:
        size: 2
  thymeleaf:
    mode: HTML
  # ===================================================================
  # Spring AI Configuration
  # ===================================================================
  ai:
    # OpenAI Configuration
    openai:
      api-key: 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
      chat:
        options:
          model: ${SPRING_AI_OPENAI_MODEL:gpt-4o-mini}
          temperature: ${SPRING_AI_OPENAI_TEMPERATURE:0.7}
          max-tokens: ${SPRING_AI_OPENAI_MAX_TOKENS:2000}

    # Ollama Configuration
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${SPRING_AI_OLLAMA_MODEL:llama3.1:8b}
          temperature: ${SPRING_AI_OLLAMA_TEMPERATURE:0.7}

    # Vector Store Configuration
    vectorstore:
      pinecone:
        api-key: pcsk_3oXyjD_3jT5c1edezEQGjTGCBeJKoJcWPPvWEZPaeYUbyQfykeDHfdkeh4YJHW5LVL7jJV
        environment: us-east1-gcp
        project-id: b0601883-f4dd-44a9-ad66-06de3d9c11e1
        index-name: satori-spring-ai

  output:
    ansi:
      console-available: true

server:
  servlet:
    session:
      cookie:
        http-only: true

springdoc:
  show-actuator: true

# Properties to be exposed on the /info management endpoint
info:
  # Comma separated list of profiles that will trigger the ribbon to show
  display-ribbon-on-profiles: 'dev'

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  clientApp:
    name: 'onlineSatoriPlatformApp'
  # By default CORS is disabled. Uncomment to enable.
  # cors:
  #   allowed-origins: "http://localhost:8100,http://localhost:9000,http://localhost:8081,http://localhost"
  #   allowed-methods: "*"
  #   allowed-headers: "*"
  #   exposed-headers: "Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params"
  #   allow-credentials: true
  #   max-age: 1800
  mail:
    from: onlineSatoriPlatform@localhost
  api-docs:
    default-include-pattern: /api/**
    management-include-pattern: /management/**
    title: Online Satori Platform API
    description: Online Satori Platform API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license: unlicensed
    license-url:
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"

# jhipster-needle-add-application-yaml-document
---
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

# ===================================================================
# AI Service Configuration
# ===================================================================
app:
  ai:
    # LangChain4J Enhanced AI Configuration
    langchain4j:
      enabled: ${LANGCHAIN4J_ENABLED:false} # Temporarily disable during Spring AI migration
    # Primary AI Provider - FREE Gemini
    gemini:
      enabled: ${GEMINI_ENABLED:true}
      api-key: ${GEMINI_API_KEY:}
      model: ${GEMINI_MODEL:gemini-1.5-flash}
      temperature: ${GEMINI_TEMPERATURE:0.7}
      timeout: ${GEMINI_TIMEOUT_SECONDS:60}
    # Local AI - Ollama (100% FREE)
    ollama:
      enabled: ${OLLAMA_ENABLED:false}
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      model: ${OLLAMA_MODEL:llama3.1:8b}
      temperature: ${OLLAMA_TEMPERATURE:0.7}
      timeout: ${OLLAMA_TIMEOUT_SECONDS:60}
    # Fast AI - Groq (FREE tier available)
    groq:
      enabled: ${GROQ_ENABLED:false}
      api-key: ${GROQ_API_KEY:}
      model: ${GROQ_MODEL:llama-3.1-8b-instant}
      temperature: ${GROQ_TEMPERATURE:0.7}
      timeout: ${GROQ_TIMEOUT_SECONDS:30}

    # DataStax Astra DB Vector Store Configuration
    astra:
      enabled: ${ASTRA_ENABLED:true}
      token: ${ASTRA_TOKEN:}
      database-id: ${ASTRA_DATABASE_ID:}
      database-region: ${ASTRA_DATABASE_REGION:us-east1}
      keyspace: ${ASTRA_KEYSPACE:default_keyspace}
      table: ${ASTRA_TABLE:japanese_learning_embeddings}
      dimension: ${ASTRA_DIMENSION:768} # For Gemini embeddings

    # ===================================================================
    # Spring AI Configuration (NEW - Migration from LangChain4J)
    # ===================================================================
    spring-ai:
      enabled: ${SPRING_AI_ENABLED:true}
      provider: ${SPRING_AI_PROVIDER:openai} # Choose 'openai' or 'ollama'
      # OpenAI Support (replaces langchain4j-open-ai)
      openai:
        enabled: ${SPRING_AI_OPENAI_ENABLED:true} # Enable OpenAI by default for Spring AI
        api-key: ${OPENAI_API_KEY:}
        chat:
          options:
            model: ${SPRING_AI_OPENAI_MODEL:gpt-4o-mini}
            temperature: ${SPRING_AI_OPENAI_TEMPERATURE:0.7}
            max-tokens: ${SPRING_AI_OPENAI_MAX_TOKENS:2000}
        embedding:
          enabled: ${SPRING_AI_OPENAI_EMBEDDING_ENABLED:true} # Enable OpenAI embeddings
          options:
            model: ${SPRING_AI_OPENAI_EMBEDDING_MODEL:text-embedding-3-small}

      # Ollama Support (replaces langchain4j-ollama)
      ollama:
        enabled: ${SPRING_AI_OLLAMA_ENABLED:false}
        base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
        chat:
          enabled: ${SPRING_AI_OLLAMA_CHAT_ENABLED:false}
          options:
            model: ${SPRING_AI_OLLAMA_MODEL:llama3.1:8b}
            temperature: ${SPRING_AI_OLLAMA_TEMPERATURE:0.7}
        embedding:
          enabled: false # Disable Ollama embeddings to avoid conflicts

      # Vector Store Configuration
      vectorstore:
        pinecone:
          enabled: ${SPRING_AI_PINECONE_ENABLED:true}
          api-key: ${PINECONE_API_KEY:}
          environment: ${PINECONE_ENVIRONMENT:us-east1-gcp}
          project-id: ${PINECONE_PROJECT_ID:}
          index-name: ${SPRING_AI_PINECONE_INDEX:satori-spring-ai}

      # RAG Configuration for Spring AI
      rag:
        enabled: ${SPRING_AI_RAG_ENABLED:true}
        similarity-threshold: ${SPRING_AI_RAG_SIMILARITY_THRESHOLD:0.7}
        top-k: ${SPRING_AI_RAG_TOP_K:5}
        retrieval:
          enabled: ${SPRING_AI_RAG_RETRIEVAL_ENABLED:true}
        augmentation:
          enabled: ${SPRING_AI_RAG_AUGMENTATION_ENABLED:true}

    # Enhanced RAG Configuration for LangChain4J
    rag:
      max-results: ${RAG_MAX_RESULTS:5}
      min-score: ${RAG_MIN_SCORE:0.6}
      chunk-size: ${RAG_CHUNK_SIZE:500}
      chunk-overlap: ${RAG_CHUNK_OVERLAP:50}
      similarity-threshold: ${LANGCHAIN4J_SIMILARITY_THRESHOLD:0.7}
      retrieval-enabled: ${LANGCHAIN4J_RETRIEVAL_ENABLED:true}

    service:
      url: ${AI_SERVICE_URL:}
      api-key: ${AI_SERVICE_API_KEY:}
      timeout: ${AI_SERVICE_TIMEOUT:30000}
      enabled: ${AI_SERVICE_ENABLED:false}
      model: ${AI_SERVICE_MODEL:gpt-3.5-turbo}
      max-tokens: ${AI_SERVICE_MAX_TOKENS:2000}
    practice-test:
      default-question-count: ${AI_PRACTICE_TEST_DEFAULT_QUESTIONS:10}
      max-question-count: ${AI_PRACTICE_TEST_MAX_QUESTIONS:50}
      fallback-enabled: ${AI_PRACTICE_TEST_FALLBACK_ENABLED:true}
  rag:
    enabled: ${RAG_ENABLED:false}
    vector-db:
      type: postgresql # postgresql or pinecone
      postgresql:
        url: ${RAG_POSTGRES_URL:jdbc:postgresql://localhost:5432/satori_vectors}
        username: ${RAG_POSTGRES_USERNAME:satori_user}
        password: ${RAG_POSTGRES_PASSWORD:satori_pass}
        table-name: ${RAG_POSTGRES_TABLE:content_embeddings}
      pinecone:
        url: ${RAG_PINECONE_URL:https://satori-spring-ai-vcm2km1.svc.aped-4627-b74a.pinecone.io}
        api-key: ${RAG_PINECONE_API_KEY:pcsk_3oXyjD_3jT5c1edezEQGjTGCBeJKoJcWPPvWEZPaeYUbyQfykeDHfdkeh4YJHW5LVL7jJV}
        index-name: ${RAG_PINECONE_INDEX:satori-spring-ai}
    embedding:
      provider: gemini # gemini or openai
      gemini:
        api-key: ${GEMINI_API_KEY:}
        model: ${GEMINI_EMBEDDING_MODEL:text-embedding-004}
        dimensions: ${GEMINI_EMBEDDING_DIMENSIONS:768}
        base-url: ${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}
      openai:
        api-key: ${OPENAI_API_KEY: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}
        model: ${OPENAI_EMBEDDING_MODEL:text-embedding-ada-002}
        dimensions: ${OPENAI_EMBEDDING_DIMENSIONS:1536}
        base-url: https://openrouter.ai/api/v1

  # ===================================================================
  # Application specific properties
  # ===================================================================
  oauth2:
    enabled: ${OAUTH2_ENABLED:true}
    redirect-base-url: ${OAUTH2_REDIRECT_BASE_URL:http://localhost:8080}
    encryption:
      key: ${OAUTH2_ENCRYPTION_KEY:}
    token:
      refresh-threshold-minutes: ${OAUTH2_TOKEN_REFRESH_THRESHOLD_MINUTES:5}
      default-expiry-hours: ${OAUTH2_TOKEN_DEFAULT_EXPIRY_HOURS:1}
      cleanup-days: ${OAUTH2_TOKEN_CLEANUP_DAYS:30}
    cleanup:
      enabled: ${OAUTH2_CLEANUP_ENABLED:true}
      unused-account-days: ${OAUTH2_CLEANUP_UNUSED_ACCOUNT_DAYS:30}
      batch-size: ${OAUTH2_CLEANUP_BATCH_SIZE:100}
    providers:
      google:
        enabled: ${GOOGLE_OAUTH2_ENABLED:true}
        client-id: ${GOOGLE_CLIENT_ID:}
        client-secret: ${GOOGLE_CLIENT_SECRET:}
        scope: openid,profile,email
        additional-parameters:
          access_type: offline
          prompt: consent
      facebook:
        enabled: ${FACEBOOK_OAUTH2_ENABLED:true}
        client-id: ${FACEBOOK_CLIENT_ID:}
        client-secret: ${FACEBOOK_CLIENT_SECRET:}
        scope: email,public_profile
      github:
        enabled: ${GITHUB_OAUTH2_ENABLED:true}
        client-id: ${GITHUB_CLIENT_ID:}
        client-secret: ${GITHUB_CLIENT_SECRET:}
        scope: user:email,read:user
  rate-limiting:
    default-requests-per-minute: 60
    auth-requests-per-minute: 5
    file-upload-requests-per-minute: 10
    api-requests-per-minute: 100
    quiz-submission-requests-per-minute: 2
    notification-requests-per-minute: 20
    ban-duration-minutes: 15
    max-failed-attempts: 5
  file-storage:
    path: uploads
    max-file-size: 50MB
  security:
    audit-log:
      enabled: true
      retention-days: 90
    input-validation:
      enabled: true
      sanitize-html: true
    rate-limiting:
      enabled: true
