package com.satori.platform.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TeacherProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeacherProfileAllPropertiesEquals(TeacherProfile expected, TeacherProfile actual) {
        assertTeacherProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertTeacherProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeacherProfileAllUpdatablePropertiesEquals(TeacherProfile expected, TeacherProfile actual) {
        assertTeacherProfileUpdatableFieldsEquals(expected, actual);
        assertTeacherProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeacherProfileAutoGeneratedPropertiesEquals(TeacherProfile expected, TeacherProfile actual) {
        assertThat(actual)
            .as("Verify TeacherProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeacherProfileUpdatableFieldsEquals(TeacherProfile expected, TeacherProfile actual) {
        assertThat(actual)
            .as("Verify TeacherProfile relevant properties")
            .satisfies(a -> assertThat(a.getTeacherCode()).as("check teacherCode").isEqualTo(expected.getTeacherCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeacherProfileUpdatableRelationshipsEquals(TeacherProfile expected, TeacherProfile actual) {
        // empty method
    }
}
